title: AgentDock RFAs
description: Request For Agents - Build powerful AI agents with AgentDock
theme: jekyll-theme-minimal

# Site settings
baseurl: "/AgentDock-Core/_rfa"
url: "https://agentdock.github.io"
source: ".."  # Look for content in parent directory
destination: "../_site"  # Output to _site in parent directory

# Build settings
include:
  - "README.md"
  - "agents"
  - "template.md"
  - "CONTRIBUTING.md"

# Collections
collections:
  agents:
    output: true
    permalink: /agents/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "agents"
    values:
      layout: "rfa"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable mermaid diagrams
mermaid:
  version: "9.1.7" 