# Site Settings
title: AgentDock Documentation
description: Documentation for AgentDock Core and RFAs

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Collections - RFAs
collections:
  agents:
    output: true
    permalink: /rfa/agents/:slug  # Clean URLs: /rfa/agents/code-reviewer

# Default layout
defaults:
  - scope:
      path: "rfa"
    values:
      layout: "rfa"
  - scope:
      path: ""
    values:
      layout: "default"

# Enable mermaid diagrams
mermaid:
  version: "9.1.7" 